### ISSUE TITLE
消息的调用方法，使用反射会有性能问题吗？

### ISSUE THREAD

**Issue by 15951836388** [zllangct/RockGO#3]
看了代码，消息的调用是用反射来实现的，不用手动一条一条的注册调用方法，很方便。

反射调用方法和普通调用方法的性能相差多少？

**Comment by zllangct** [comment]
使用反射性能折扣是必然的，反射也有很多种，这里的性能折扣比较小，性能不是问题

**Comment by zllangct** [comment]
消息的主要消耗，在消息的反序列化，反射带来的这个性能消耗是九牛一毛

**Comment by 15951836388** [comment]
好的，谢谢。有考虑过客户端和服务器之间也用grpc吗？

**Comment by zllangct** [comment]
不现实，rpc不是这么用的~这是个误区，你要实现客户端和服务端同步调用的功能，其实在客户端封装一下就好
