### ISSUE TITLE
房间类游戏大厅、房间模型

### ISSUE THREAD

**Issue by ruifly2012** [zllangct/RockGO#4]
框架很不错房间类游戏大厅、房间模型目前有计划吗

**Comment by zllangct** [comment]
棋牌休闲类的朋友需求量还挺大，这几天好多问这个的，答案是会提供的，这一段时间，自己项目和某商业项目一起，先落实一个项目，把整体结构和API稳定下来，交给用户的应该是稳定可靠的，性能上的调优，比如系统的遍历部分，肯定还会升级。房间类模型本身不复杂，后续我会提供一个参考，当然这个实现方式很多，一般的开发者自己都能搞得，可能才入行的比较需要这个来快速搭建小项目。
