### ISSUE TITLE
有qq群吗

### ISSUE THREAD

**Issue by luohong520** [zllangct/RockGO#5]

**Comment by zllangct** [comment]
暂时没有，完成全部文档和example，通过一个商业项目的稳定性测试之后，再开始宣传，半成品不合适太激进，所以目前还没有打算建立用户群，目前而言，可用，但是有些坑需要自己填，稳定性得不到保证，使用开源框架的新手比较多，他们需要更为完善的作品，对于有经验的开发者，框架源码在此，足够交流了，计划中有些地方还有较大改动，541639809@qq.com，有好的改进意见，可以联系我。
