### ISSUE TITLE
何时更新最新版？学习学习

### ISSUE THREAD

**Issue by KyleHansT** [zllangct/RockGO#6]

**Comment by zllangct** [comment]
小蜜蜂正在努力测试中，ECS逻辑整体方向不变，重构了ECS，实现system按兴趣缓存组件遍历，剥离entity的树形结构，组件间本身低耦合，底层对系统分组，竞态数据同线程，在ecs构架内实现0数据竞争，严格ecs下，可实现无锁化。

**Comment by magix** [comment]
期待中

**Comment by bournes** [comment]
期待更新！！！！

**Comment by magix** [comment]
期待您的更新。

**Comment by zllangct** [comment]
半个月左右
